### ISSUE TITLE
odroid_u3: problem: Unable to boot u3 & u3+ with release 230224-05

### ISSUE THREAD

**Issue by gociii** [hexdump0815/imagebuilder#138]
Hi hexdump - thought I'd let you know that having tried burning this img twice for u3 & u3+, I was unable to boot. Blue LED not flashing at all after power up.

**Comment by hexdump0815** [comment]
@gociii - i think i know what the problem is: this commit https://github.com/hexdump0815/imagebuilder/commit/793423b50929fd9b66d7b19585fe1a4ecf276a63 is breaking the boot blocks at least on the odroid, but maybe on other systems too - i'll build and upload new images and let you know when they are ready

**Comment by hexdump0815** [comment]
@gociii - i have uploaded an image with fixed bootloader which should work (at least it does for me now) ... as a bonus there is now also an ubuntu jammy image as well :)

https://github.com/hexdump0815/imagebuilder/releases/tag/230224-05

thanks once more for reporting this problem

**Comment by gociii** [comment]
You're a star🌟 ! Will try it in a couple of hours and let you know.

**Comment by gociii** [comment]
This is fixed :) Thanks.
